In [1]:
import pandas as pd

In [2]:
# spectral 18
spec_18 = pd.read_csv('Spectral_1/permute_p_values_GOBP.csv',sep='\t')
spec_18.head(10)

,C,Cn,GO:0000165,actual overlap,expected overlap,OR,95% CI,p-value,p.adjusted,{p_value},...,OR.61,95% CI.61,p-value.61,p.adjusted.61,{p_value}.61,BC.61,p-value(ALT).61,p.adjusted(ALT).61,BC(ALT).61,Unnamed: 746
0,1,22,122,0,2.15929,0.000000,"[0.00,0.00]",1.000000,1.0,0.1,...,0.0000,"[0.00,0.00]",1.000000,1,0.1,NaN,1.000000,1,NaN,NaN
1,2,22,122,0,2.15929,0.000000,"[0.00,0.00]",1.000000,1.0,0.1,...,0.0000,"[0.00,0.00]",1.000000,1,0.1,NaN,1.000000,1,NaN,NaN
2,3,35,122,1,3.43524,0.264220,"[0.04,1.95]",0.125696,1.0,0.1,...,0.0000,"[0.00,0.00]",1.000000,1,0.1,NaN,1.000000,1,NaN,NaN
3,4,73,122,10,7.16492,1.499430,"[0.75,3.00]",0.135424,1.0,0.1,...,0.0000,"[0.00,0.00]",1.000000,1,0.1,NaN,1.000000,1,NaN,NaN
4,5,22,122,0,2.15929,0.000000,"[0.00,0.00]",1.000000,1.0,0.1,...,0.0000,"[0.00,0.00]",1.000000,1,0.1,NaN,1.000000,1,NaN,NaN
5,6,21,122,0,2.06114,0.000000,"[0.00,0.00]",1.000000,1.0,0.1,...,0.0000,"[0.00,0.00]",1.000000,1,0.1,NaN,1.000000,1,NaN,NaN
6,7,24,122,6,2.35559,3.169540,"[1.23,8.14]",0.018031,1.0,0.1,...,4.7747,"[0.59,38.54]",0.188478,1,0.1,NaN,0.979036,1,NaN,NaN
7,8,16,122,1,1.57039,0.609366,"[0.08,4.65]",0.523879,1.0,0.1,...,0.0000,"[0.00,0.00]",1.000000,1,0.1,NaN,1.000000,1,NaN,NaN
8,9,18,122,1,1.76669,0.536704,"[0.07,4.07]",0.459293,1.0,0.1,...,0.0000,"[0.00,0.00]",1.000000,1,0.1,NaN,1.000000,1,NaN,NaN
9,10,58,122,1,5.69268,0.154270,"[0.02,1.12]",0.016463,1.0,0.1,...,0.0000,"[0.00,0.00]",1.000000,1,0.1,NaN,1.000000,1,NaN,NaN

In [42]:
# s = spec_18.filter(like='p-value')
s = spec_18.filter(like='p.adjusted')
# s = spec_18.filter(like='95%')
s.head()

,p.adjusted,p.adjusted(ALT),p.adjusted.1,p.adjusted(ALT).1,p.adjusted.2,p.adjusted(ALT).2,p.adjusted.3,p.adjusted(ALT).3,p.adjusted.4,p.adjusted(ALT).4,...,p.adjusted.57,p.adjusted(ALT).57,p.adjusted.58,p.adjusted(ALT).58,p.adjusted.59,p.adjusted(ALT).59,p.adjusted.60,p.adjusted(ALT).60,p.adjusted.61,p.adjusted(ALT).61
0,1.0,1,1,1,1.0,1,1,1,1.000000,1,...,1.00000,1,1,1,1,1,1.0,1,1,1
1,1.0,1,1,1,1.0,1,1,1,1.000000,1,...,1.00000,1,1,1,1,1,1.0,1,1,1
2,1.0,1,1,1,1.0,1,1,1,1.000000,1,...,1.00000,1,1,1,1,1,1.0,1,1,1
3,1.0,1,1,1,1.0,1,1,1,0.139259,1,...,0.75724,1,1,1,1,1,1.0,1,1,1
4,1.0,1,1,1,1.0,1,1,1,1.000000,1,...,1.00000,1,1,1,1,1,1.0,1,1,1

In [201]:
community_no = 50


check_95 = True
check_95 = False


if_ac = False
# if_ac = True

s = spec_18.filter(like='p-value')
s = spec_18.filter(like='p.adjusted')



if(check_95):
    s = spec_18.filter(like='95%')
#     s = spec_18.filter(like='OR')

if(if_ac):
#     s = spec_18.filter(like='expected')
    s = spec_18.filter(like='actual')
    check_95 = True
    
s_0 = s.iloc[community_no - 1,:]

s_0.sort_values(ascending=(not check_95))

p.adjusted            0.786181
p.adjusted.45         1.000000
p.adjusted(ALT).44    1.000000
p.adjusted.44         1.000000
p.adjusted(ALT).43    1.000000
p.adjusted.43         1.000000
p.adjusted(ALT).42    1.000000
p.adjusted.42         1.000000
p.adjusted(ALT).41    1.000000
p.adjusted.41         1.000000
p.adjusted(ALT).40    1.000000
p.adjusted.40         1.000000
p.adjusted(ALT).39    1.000000
p.adjusted.39         1.000000
p.adjusted(ALT).38    1.000000
p.adjusted.38         1.000000
p.adjusted(ALT).37    1.000000
p.adjusted.37         1.000000
p.adjusted(ALT).36    1.000000
p.adjusted.36         1.000000
p.adjusted(ALT).35    1.000000
p.adjusted.35         1.000000
p.adjusted(ALT).34    1.000000
p.adjusted.34         1.000000
p.adjusted(ALT).33    1.000000
p.adjusted.33         1.000000
p.adjusted(ALT).32    1.000000
p.adjusted.32         1.000000
p.adjusted(ALT).45    1.000000
p.adjusted(ALT).31    1.000000
                        ...
p.adjusted(ALT).29    1.000000
p.adjusted.29         1.000000
p.adjusted(ALT).28    1.000000
p.adjusted.28         1.000000
p.adjusted(ALT).27    1.000000
p.adjusted.27         1.000000
p.adjusted(ALT).26    1.000000
p.adjusted.26         1.000000
p.adjusted(ALT).25    1.000000
p.adjusted.25         1.000000
p.adjusted(ALT).24    1.000000
p.adjusted.24         1.000000
p.adjusted(ALT).23    1.000000
p.adjusted.61         1.000000
p.adjusted.23         1.000000
p.adjusted.22         1.000000
p.adjusted(ALT).21    1.000000
p.adjusted.21         1.000000
p.adjusted(ALT).20    1.000000
p.adjusted.20         1.000000
p.adjusted(ALT).19    1.000000
p.adjusted.19         1.000000
p.adjusted(ALT).18    1.000000
p.adjusted.18         1.000000
p.adjusted(ALT).17    1.000000
p.adjusted.17         1.000000
p.adjusted(ALT).16    1.000000
p.adjusted.16         1.000000
p.adjusted(ALT).22    1.000000
p.adjusted(ALT).61    1.000000
Name: 49, Length: 124, dtype: float64