In [1]:
import pandas as pd

In [3]:


# induvidual enrichments
Dis_en = 'RESULTS/PPI_Network/sgG5/permute_p_values_HDO.csv'
BP_en = 'RESULTS/PPI_Network/sgG5/permute_p_values_GOBP.csv'
DE_en = 'OUT/permute_p_values_DE_sgG5.csv'


# comparison enrichment 
Dis_BP_en = 'OUT/Comparisions/overlapCOMS_BPvsDE.csv'
Dis_DE_en = 'OUT/Comparisions/overlapCOMS_BPvsDisb.csv'
BP_DE_en  = 'OUT/Comparisions/overlapCOMS_DEvsDis.csv'

In [19]:
thefile = pd.read_csv(BP_en,sep='\t')
thefile.head()

,C,Cn,GO:0000165,actual overlap,expected overlap,OR,95% CI,p-value,p.adjusted,{p_value},...,OR.61,95% CI.61,p-value.61,p.adjusted.61,{p_value}.61,BC.61,p-value(ALT).61,p.adjusted(ALT).61,BC(ALT).61,Unnamed: 746
0,1,17,122,0,1.668540,0.000000,"[0.00,0.00]",1.000000,1.0,0.1,...,0.0,"[0.00,0.00]",1.0,1,0.1,NaN,1.0,1,NaN,NaN
1,2,13,122,1,1.275950,0.763774,"[0.10,5.92]",0.630069,1.0,0.1,...,0.0,"[0.00,0.00]",1.0,1,0.1,NaN,1.0,1,NaN,NaN
2,3,13,122,0,1.275950,0.000000,"[0.00,0.00]",1.000000,1.0,0.1,...,0.0,"[0.00,0.00]",1.0,1,0.1,NaN,1.0,1,NaN,NaN
3,4,15,122,1,1.472240,0.653483,"[0.09,5.01]",0.558146,1.0,0.1,...,0.0,"[0.00,0.00]",1.0,1,0.1,NaN,1.0,1,NaN,NaN
4,5,3,122,0,0.294449,0.000000,"[0.00,0.00]",1.000000,1.0,0.1,...,0.0,"[0.00,0.00]",1.0,1,0.1,NaN,1.0,1,NaN,NaN

In [94]:
community_no = 1

check_95 = True
check_95 = False

if_ac = False
# if_ac = True

s = thefile.filter(like='p-value')
# s = thefile.filter(like='p.adjusted')

if(check_95):
    s = thefile.filter(like='95%')
#     s = thefile.filter(like='OR')

if(if_ac):
    s = thefile.filter(like='expected')
    s = thefile.filter(like='actual')
    check_95=True

s_0 = s.iloc[community_no -1,:]

# s_0.sort_values(ascending=(not check_95))

In [126]:
community_no = 8
s_c = thefile.iloc[community_no - 1,:]
df = pd.DataFrame()
pvals = [a[0]]
b = list(s_c.filter(regex='p-value(?:[^\(alt\)]+)|p-value '))
pvals = pvals + b
df['pv'] = pvals
b = list(s_c.filter(regex='p.adjusted(?:[^\(alt\)]+)'))
b1 = [list(s_c.filter(like='p.adjusted'))[0]]
colnames = thefile.columns.values
GOterms = [item for item in colnames if 'GO' in item]
df['padj'] = b1 + b #list(s_c.filter(like='p.adjusted'))
df['95'] = list(s_c.filter(like='95%'))
df['actual'] = list(s_c.filter(like='actual'))
df['exptected'] = list(s_c.filter(like='expected'))
df['GO'] = GOterms
sorted_df = df.sort_values(by=['pv'])
print('Community number:' + str(community_no))
print((sorted_df.index[0] * 12) + 3)
sorted_df.head(10)

Community number:8
135

          pv  padj            95  actual  exptected          GO
11  0.011664   1.0  [2.03,27.16]       3   0.514883  GO:0007411
3   0.115346   1.0  [1.07,75.76]       1   0.128721  GO:0002224
6   0.325804   1.0  [0.25,14.95]       1   0.540628  GO:0002758
2   0.329395   1.0  [0.24,14.58]       1   0.553500  GO:0002218
5   0.381300   1.0   [0.14,8.33]       1   0.926790  GO:0002757
9   0.514949   1.0   [0.08,4.57]       1   1.596140  GO:0007268
55  0.514949   1.0   [0.08,4.57]       1   1.596140  GO:0099536
56  0.514949   1.0   [0.08,4.57]       1   1.596140  GO:0099537
33  0.749246   1.0   [0.14,7.97]       1   0.965406  GO:0050804
44  1.000000   1.0   [0.00,0.00]       0   0.051488  GO:0060563

In [120]:
len(pvals)
print(len(b))
colnames = thefile.columns.values
# s_c.filter(like='GO')
GOterms = [item for item in colnames if 'GO' in item] 
len(GOterms)
#.filter(like='GO')

61

62