In [7]:
import pandas as pd

In [22]:
thefile  = pd.read_csv('PPI_Network/PPI_Network_Measures.csv',sep='\t',index_col='ENTREZ.ID')

thefile.head()

diff3 = pd.read_csv('Diff_exp3.csv',header=None)
diff3 = list(diff3[0])
diff2 = pd.read_csv('Diff_exp2.csv',header=None)
diff2 = list(diff2[0])
diff = pd.read_csv('Diffrentially_Expressed.csv',header=None)
diff = list(diff[0])
# diff3

thefile['DE'] = 0
thefile.head()

diff3

[10801, 4735, 6853, 80725]

In [23]:
thefile.columns.values
thefile.index
# thefile.loc[[273,1759,1785]]

a = [93185, 4099, 2819, 134, 2823, 4744, 84617, 3848, 3849, 79751, 526, 9615, 219537, 3858, 4884, 794, 5019, 3615, 4897, 2596, 292, 25769, 25902, 50, 348980, 308, 1462, 1345, 961, 55753, 586, 203, 2892, 2891, 2893, 4817, 8402, 54996, 478, 5091, 4199, 5095, 622, 6512, 100526833, 23154, 7923, 4724, 1653, 4340, 4978, 126328, 55163, 57468, 8574]
len(a)
len(diff)
# diff = diff - a
diff = [x for x in diff if x not in a]
a = [9751, 3848, 2891, 2892, 2893, 3858, 23154, 478,79751]
diff2 = [x for x in diff2 if x not in a]

thefile.loc[diff,['DE']] = 1
thefile.loc[diff3,['DE']] = 3
thefile.loc[diff2,['DE']] = 2
# thefile.head()
thefile.loc[diff3]

thefile.loc[diff]
# len(thefile)
# thefile.to_csv('Measures_with_DE.csv')

,GENE.NAME,DEGREE,Closeness,Bet,CC,Cl,Clnorm,SP,PR,sgG5,BRIDGE_sgG5,PROB_sgG5,MIX_sgG5,BR_CONSENSUS,BR_CONSENSUS_MAD,BR_CONSENSUS_ADJ,DE
ENTREZ.ID,,,,,,,,,,,,,,,,,
2617,2617,3,0.277,216.533869,0.000000,15696,0.071741,2,0.000479,49,0.358334,0.991976,0.666667,0.358334,0,0.286215,1
3190,3190,16,0.304,7464.171467,0.100000,31584,0.144414,2,0.002194,36,0.328946,1.000000,0.375000,0.328946,0,0.156612,1
3094,3094,1,0.234,0.000000,NaN,2172,0.009880,3,0.000235,26,0.000000,0.995560,0.000000,0.000000,0,-1.294023,1
10130,10130,4,0.263,1616.165675,0.166667,9148,0.041789,3,0.000793,81,0.247941,1.000000,0.250000,0.247941,0,-0.200614,1
9318,9318,3,0.267,192.666251,0.333333,9996,0.045668,3,0.000519,47,0.284179,0.999774,0.333333,0.284179,0,-0.040805,1
5682,5682,18,0.302,11399.258147,0.052288,29557,0.135143,3,0.002509,87,0.558038,1.000000,0.611111,0.558038,0,1.166898,2
5702,5702,5,0.240,2186.210476,0.200000,2742,0.012487,3,0.000906,85,0.176432,1.000000,0.200000,0.176432,0,-0.515967,1
5704,5704,7,0.266,1497.935551,0.095238,10718,0.048971,2,0.000985,85,0.472751,1.000000,0.571429,0.472751,0,0.790785,1
5049,5049,5,0.264,1469.827651,0.100000,8677,0.039635,2,0.000759,71,0.497032,0.999839,0.600000,0.497032,0,0.897864,1
348,348,14,0.298,6233.179779,0.032967,25439,0.116306,2,0.001986,88,0.621853,1.000000,0.571429,0.621853,0,1.448317,2
8682,8682,14,0.279,7466.147863,0.021978,16457,0.075222,3,0.002339,2,0.465838,1.000000,0.500000,0.465838,0,0.760301,1
3251,3251,1,0.239,0.000000,NaN,4005,0.018264,3,0.000246,75,0.000000,0.993792,0.000000,0.000000,0,-1.294023,1
5604,5604,4,0.266,456.428832,0.166667,10248,0.046821,3,0.000600,78,0.415055,0.999248,0.500000,0.415055,0,0.536349,1
7018,7018,4,0.275,521.932564,0.000000,15553,0.071086,2,0.000613,73,0.415055,0.999937,0.500000,0.415055,0,0.536349,1
1428,1428,1,0.258,0.000000,NaN,6053,0.027632,2,0.000229,33,0.000000,0.980497,0.000000,0.000000,0,-1.294023,1
6843,6843,4,0.243,219.250282,0.500000,4914,0.022422,3,0.000649,44,0.000000,1.000000,0.000000,0.000000,0,-1.294023,1
6616,6616,8,0.296,4578.337108,0.107143,26635,0.121777,1,0.001320,44,0.397061,1.000000,0.375000,0.397061,0,0.456996,2
112755,112755,6,0.227,742.785820,0.200000,2706,0.012323,3,0.000988,44,0.000000,1.000000,0.000000,0.000000,0,-1.294023,2
22848,22848,1,0.235,0.000000,NaN,3026,0.013786,3,0.000248,13,0.000000,0.995392,0.000000,0.000000,0,-1.294023,1
9522,9522,7,0.255,742.700205,0.142857,8643,0.039479,3,0.000990,42,0.390306,1.000000,0.428571,0.390306,0,0.427207,2
11346,11346,3,0.261,54.863901,0.333333,9635,0.044017,2,0.000446,79,0.284179,0.999691,0.333333,0.284179,0,-0.040805,1
22941,22941,12,0.296,844.472869,0.181818,38576,0.176397,2,0.001425,23,0.512547,0.999999,0.583333,0.512547,0,0.966285,1
50944,50944,6,0.281,448.648784,0.000000,14013,0.064042,2,0.000788,73,0.568226,0.983250,0.833333,0.568226,0,1.211826,1
9568,9568,3,0.257,148.419137,0.000000,4147,0.018914,2,0.000496,71,0.296768,0.999943,0.333333,0.296768,0,0.014712,1
6529,6529,1,0.228,0.000000,NaN,2175,0.009894,3,0.000257,44,0.000000,0.993060,0.000000,0.000000,0,-1.294023,1
6506,6506,1,0.270,0.000000,NaN,12874,0.058832,2,0.000232,55,0.000000,0.987190,0.000000,0.000000,0,-1.294023,1
490,490,4,0.282,1067.151899,0.166667,19615,0.089667,3,0.000616,47,0.458637,0.967036,0.750000,0.458637,0,0.728543,1
477,477,1,0.225,0.000000,NaN,1550,0.007035,3,0.000242,65,0.000000,0.996195,0.000000,0.000000,0,-1.294023,1
476,476,5,0.264,2736.010521,0.100000,9471,0.043267,2,0.000869,78,0.176432,1.000000,0.200000,0.176432,0,-0.515967,1
5906,5906,8,0.271,2084.149571,0.035714,12731,0.058178,2,0.001221,83,0.404219,1.000000,0.500000,0.404219,0,0.488563,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80725,80725,1,0.229,0.000000,NaN,1048,0.004739,2,0.000261,44,0.000000,0.993060,0.000000,0.000000,0,-1.294023,3
8831,8831,3,0.258,282.755685,0.333333,6778,0.030949,3,0.000464,7,0.296768,0.999849,0.333333,0.296768,0,0.014712,2
9456,9456,3,0.243,48.322723,0.000000,5886,0.026868,3,0.000458,89,0.358334,0.994803,0.666667,0.358334,0,0.286215,2
2890,2890,2,0.253,37.684514,0.000000,4397,0.020058,3,0.000371,53,0.293432,0.992410,0.500000,0.293432,0,0.000000,2
1742,1742,17,0.292,5447.077212,0.066176,31875,0.145745,2,0.002185,7,0.528166,1.000000,0.529412,0.528166,0,1.035162,1
5682,5682,18,0.302,11399.258147,0.052288,29557,0.135143,3,0.002509,87,0.558038,1.000000,0.611111,0.558038,0,1.166898,2
815,815,13,0.304,2758.898987,0.179487,39953,0.182695,2,0.001558,33,0.578673,0.999998,0.615385,0.578673,0,1.257896,2
287,287,4,0.277,1252.418847,0.000000,15240,0.069655,2,0.000646,64,0.458637,0.989963,0.750000,0.458637,0,0.728543,2
816,816,10,0.291,1645.398097,0.244444,28213,0.128995,2,0.001300,33,0.482571,1.000000,0.500000,0.482571,0,0.834093,1
8997,8997,2,0.230,85.159257,0.000000,2340,0.010649,3,0.000415,66,0.000000,0.999968,0.000000,0.000000,0,-1.294023,1
286,286,2,0.269,75.897221,0.000000,12854,0.058741,2,0.000356,56,0.293432,0.980357,0.500000,0.293432,0,0.000000,1
1499,1499,15,0.306,7558.702336,0.028571,34568,0.158063,2,0.002015,26,0.645445,1.000000,0.666667,0.645445,0,1.552360,1
6262,6262,3,0.256,80.278943,0.000000,5457,0.024906,2,0.000463,51,0.358334,0.991969,0.666667,0.358334,0,0.286215,1
11331,11331,4,0.199,1032.418178,0.166667,417,0.001853,4,0.000904,21,0.000000,1.000000,0.000000,0.000000,0,-1.294023,1
5245,5245,4,0.197,1178.086308,0.166667,380,0.001683,3,0.000913,21,0.276367,1.000000,0.250000,0.276367,0,-0.075255,1
6708,6708,9,0.281,1465.633829,0.083333,18499,0.084562,3,0.001211,40,0.452773,0.999999,0.555556,0.452773,0,0.702684,1
6853,6853,4,0.298,358.789470,0.166667,28418,0.129933,1,0.000590,63,0.458637,0.975670,0.750000,0.458637,0,0.728543,3
6710,6710,4,0.262,113.772542,0.166667,7128,0.032549,2,0.000589,66,0.415055,0.999832,0.500000,0.415055,0,0.536349,1
8573,8573,13,0.283,4550.146961,0.025641,15881,0.072587,2,0.001860,16,0.478730,0.999999,0.692308,0.478730,0,0.817155,1
10801,10801,7,0.277,673.851354,0.285714,15818,0.072299,3,0.000952,12,0.240103,1.000000,0.285714,0.240103,0,-0.235180,3
5582,5582,3,0.268,52.797624,0.666667,13916,0.063599,2,0.000456,26,0.096376,0.999947,0.333333,0.096376,0,-0.869007,1
535,535,2,0.203,18.921527,0.000000,449,0.001999,4,0.000461,65,0.000000,0.999986,0.000000,0.000000,0,-1.294023,1
55964,55964,6,0.286,1472.796110,0.000000,14609,0.066769,2,0.000833,50,0.520192,0.999812,0.666667,0.520192,0,1.000000,1
3708,3708,6,0.258,686.222285,0.066667,5024,0.022926,2,0.000894,51,0.360727,1.000000,0.500000,0.360727,0,0.296767,2
6543,6543,1,0.216,0.000000,NaN,864,0.003897,3,0.000266,76,0.000000,0.996512,0.000000,0.000000,0,-1.294023,1
4130,4130,5,0.279,3219.966808,0.100000,16090,0.073543,2,0.000817,62,0.497032,0.999967,0.600000,0.497032,0,0.897864,2
4735,4735,6,0.271,946.511048,0.133333,12492,0.057085,3,0.000846,12,0.350718,1.000000,0.333333,0.350718,0,0.252627,3
2915,2915,1,0.243,0.000000,NaN,3191,0.014541,2,0.000232,78,0.000000,0.988279,0.000000,0.000000,0,-1.294023,1
7417,7417,3,0.226,2653.143690,0.000000,903,0.004076,2,0.000777,51,0.296768,0.999977,0.333333,0.296768,0,0.014712,1
2770,2770,4,0.234,83.745111,0.166667,3359,0.015310,3,0.000622,37,0.000000,1.000000,0.000000,0.000000,0,-1.294023,1

In [40]:
a = [93185, 4099, 2819, 134, 2823, 4744, 84617, 3848, 3849, 79751, 526, 9615, 219537, 3858, 4884, 794, 5019, 3615, 4897, 2596, 292, 25769, 25902, 50, 348980, 308, 1462, 1345, 961, 55753, 586, 203, 2892, 2891, 2893, 4817, 8402, 54996, 478, 5091, 4199, 5095, 622, 6512, 100526833, 23154, 7923, 4724, 1653, 4340, 4978, 126328, 55163, 57468, 8574]
len(a)
len(diff)

411

In [13]:
meas = pd.read_csv('Measures_with_DE.csv')
clus = pd.read_csv('../clustering/Clustering/PPI_Network/sgG5_communities.csv',sep='\t')

clus.head()

       #communities
273               32
1759              32
1785              32
26052             37
1020              32

In [37]:
thedf = pd.DataFrame()

# sorting by degrees
bydeg = meas.sort_values('DEGREE')
thedf['degrees'] =  list(bydeg['ENTREZ.ID'])
# bydeg.head(10)

#sorting by closeness
bycls = meas.sort_values('Closeness')
thedf['closeness'] = list(bycls['ENTREZ.ID'])

#sorting by bewtweennes
bybet = meas.sort_values('Bet')
thedf['bet'] = list(bybet['ENTREZ.ID'])

#sorting by local centrality
bycl = meas.sort_values('Cl')
thedf['clnorm'] = list(bycl['ENTREZ.ID'])

#sorting by bridgeness
bybr = meas.sort_values('BRIDGE_sgG5')
thedf['bridgeness'] = list(bybr['ENTREZ.ID'])

bybr = meas.sort_values('BR_CONSENSUS')
thedf['br con'] = list(bybr['ENTREZ.ID'])

c = thedf.columns.values
for index, row in thedf.iterrows():
    for i in range(len(c)):
        col = c[i]
#         print(type(thedf[col]))
#         thedf.loc[ thedf[col] in diff, col] = '*'+row[col]  
#         thedf.loc[ thedf[col] in diff2, col] = '*'+row[col]  
#         thedf.loc[ thedf[col] in diff3, col] = '**'+row[col]  

        if(row[col] in diff):
#             thedf.set_index(col,inplace=True)
            thedf.loc[thedf[col] == row[col], col] = '*' + str(row[col])
        if(row[col] in diff2):
#             thedf.set_index(col,inplace=True)
            thedf.loc[thedf[col] == row[col], col] = '*' + str(row[col])
        if(row[col] in diff3):
#             thedf.set_index(col,inplace=True)
            thedf.loc[thedf[col] == row[col], col] = '**' + str(row[col])
        

print(thedf.head(10))
bybr.head(10)

  degrees closeness    bet clnorm bridgeness br con
0     483      6217    483   6217        483    483
1    3996      9751  56267   9751      11135  11135
2    *119     *2664   5532  *2946        162    162
3   23603     *2946   3897  *2664      55770  55770
4    7464      1537   5213   1537       5372   5372
5     833      8834   3996  *4723       *989   *989
6    5297     10694   *119   8834      80124  80124
7   10768      6507   *966  54828      *2554  *2554
8     682     54828  10457  *4540      55739  55739
9    6059     *4723    873  55967       8078   8078

,ENTREZ.ID,GENE.NAME,DEGREE,Closeness,Bet,CC,Cl,Clnorm,SP,PR,sgG5,BRIDGE_sgG5,PROB_sgG5,MIX_sgG5,BR_CONSENSUS,BR_CONSENSUS_MAD,BR_CONSENSUS_ADJ,DE
1242,483,483,1,0.218,0.000000,NaN,1211,0.005484,4,0.000263,2,0.0,0.996353,0.0,0.0,0,-1.294023,0
817,11135,11135,1,0.240,0.000000,NaN,3750,0.017098,3,0.000237,74,0.0,0.990524,0.0,0.0,0,-1.294023,0
336,162,162,4,0.241,256.719513,0.000000,2933,0.013361,2,0.000691,69,0.0,1.000000,0.0,0.0,0,-1.294023,0
819,55770,55770,2,0.221,0.000000,1.000000,977,0.004414,3,0.000403,43,0.0,0.999977,0.0,0.0,0,-1.294023,0
820,5372,5372,1,0.200,0.000000,NaN,305,0.001340,4,0.000330,62,0.0,0.997622,0.0,0.0,0,-1.294023,0
822,989,989,6,0.263,20.814065,0.666667,12841,0.058681,3,0.000821,12,0.0,1.000000,0.0,0.0,0,-1.294023,2
332,80124,80124,1,0.249,0.000000,NaN,6351,0.028995,3,0.000235,54,0.0,0.988682,0.0,0.0,0,-1.294023,0
828,2554,2554,1,0.232,0.000000,NaN,2675,0.012181,3,0.000242,68,0.0,0.990008,0.0,0.0,0,-1.294023,1
831,55739,55739,2,0.240,0.000000,1.000000,5062,0.023099,3,0.000360,68,0.0,0.999902,0.0,0.0,0,-1.294023,0
328,8078,8078,1,0.249,0.000000,NaN,6351,0.028995,3,0.000235,54,0.0,0.988682,0.0,0.0,0,-1.294023,0

In [28]:
type(diff)

list